var stimulus = [
  {
    // Subject Relatives
    // #1
    s0: '<p class="stimulus">_________ | ____ | ______ | _________ | _____</p>',
    s1: '<p class="stimulus">The horse | ____ | ______ | _________ | _____</p>',
    s2: '<p class="stimulus">_________ | that | ______ | _________ | _____</p>',
    s3: '<p class="stimulus">_________ | ____ | chases | _________ | _____</p>',
    s4: '<p class="stimulus">_________ | ____ | ______ | the zebra | _____</p>',
    s5: '<p class="stimulus">_________ | ____ | ______ | _________ | falls</p>',
    clause_type: "sr",
    number: "ss",
    question: "<h2>Does the horse that chases the zebra fall?</h2>",
    correct_answer: true,
  },
  // {
  //   // #3
  //   s0: '<p class="stimulus">_________ | ____ | _____ | _________ | ______</p>',
  //   s1: '<p class="stimulus">The horse | ____ | _____ | _________ | ______</p>',
  //   s2: '<p class="stimulus">_________ | that | _____ | _________ | ______</p>',
  //   s3: '<p class="stimulus">_________ | ____ | kicks | _________ | ______</p>',
  //   s4: '<p class="stimulus">_________ | ____ | _____ | the zebra | ______</p>',
  //   s5: '<p class="stimulus">_________ | ____ | _____ | _________ | laughs</p>',
  //   clause_type: "sr",
  //   number: "ss",
  //   question: "<h2>Does the zebra that kicks the horse laugh?</h2>",
  //   correct_answer: true,
  // },
  {
    // #4
    s0: '<p class="stimulus">_________ | ____ | _______ | _________ | ____</p>',
    s1: '<p class="stimulus">The zebra | ____ | _______ | _________ | ____</p>',
    s2: '<p class="stimulus">_________ | that | _______ | _________ | ____</p>',
    s3: '<p class="stimulus">_________ | ____ | follows | _________ | ____</p>',
    s4: '<p class="stimulus">_________ | ____ | _______ | the horse | ____</p>',
    s5: '<p class="stimulus">_________ | ____ | _______ | _________ | runs</p>',
    clause_type: "sr",
    number: "ss",
    question: "<h2>Does the zebra that follows the horse run?</h2>",
    correct_answer: true,
  },
  {
    // #7
    s0: '<p class="stimulus">_______ | ____ | ______ | _______ | _____</p>',
    s1: '<p class="stimulus">The dog | ____ | ______ | _______ | _____</p>',
    s2: '<p class="stimulus">_______ | that | ______ | _______ | _____</p>',
    s3: '<p class="stimulus">_______ | ____ | pushes | _______ | _____</p>',
    s4: '<p class="stimulus">_______ | ____ | ______ | the cat | _____</p>',
    s5: '<p class="stimulus">_______ | ____ | ______ | _______ | cries</p>',
    clause_type: "sr",
    number: "ss",
    question: "<h2>Does the cat that pushes the dog cry?</h2>",
    correct_answer: false,
  },
  {
    // #8
    s0: '<p class="stimulus">_______ | ____ | ____ | _______ | ______</p>',
    s1: '<p class="stimulus">The cat | ____ | ____ | _______ | ______</p>',
    s2: '<p class="stimulus">_______ | that | ____ | _______ | ______</p>',
    s3: '<p class="stimulus">_______ | ____ | hugs | _______ | ______</p>',
    s4: '<p class="stimulus">_______ | ____ | ____ | the dog | ______</p>',
    s5: '<p class="stimulus">_______ | ____ | ____ | _______ | smiles</p>',
    clause_type: "sr",
    number: "ss",
    question: "<h2>Does the cat that hugs the dog smile?</h2>",
    correct_answer: true,
  },
  // {
  //   // #10
  //   s0: '<p class="stimulus">_______ | ____ | _______ | _______ | ____</p>',
  //   s1: '<p class="stimulus">The cat | ____ | _______ | _______ | ____</p>',
  //   s2: '<p class="stimulus">_______ | that | _______ | _______ | ____</p>',
  //   s3: '<p class="stimulus">_______ | ____ | watches | _______ | ____</p>',
  //   s4: '<p class="stimulus">_______ | ____ | _______ | the dog | ____</p>',
  //   s5: '<p class="stimulus">_______ | ____ | _______ | _______ | eats</p>',
  //   clause_type: "sr",
  //   number: "ss",
  //   question: "<h2>Does the dog that watches the cat eat?</h2>",
  //   correct_answer: false,
  // },
  {
    // #1
    s0: '<p class="stimulus">__________ | ____ | _____ | __________ | _____</p>',
    s1: '<p class="stimulus">The horses | ____ | _____ | __________ | _____</p>',
    s2: '<p class="stimulus">__________ | that | _____ | __________ | _____</p>',
    s3: '<p class="stimulus">__________ | ____ | chase | __________ | _____</p>',
    s4: '<p class="stimulus">__________ | ____ | _____ | the zebras | ____ </p>',
    s5: '<p class="stimulus">__________ | ____ | _____ | __________ | fall </p>',
    clause_type: "sr",
    number: "pp",
    question: "<h2>Do the horses that chase the zebras fall?</h2>",
    correct_answer: true,
  },
  // {
  //   // #3
  //   s0: '<p class="stimulus">__________ | ____ | ____ | __________ | _____</p>',
  //   s1: '<p class="stimulus">The horses | ____ | ____ | __________ | _____</p>',
  //   s2: '<p class="stimulus">__________ | that | ____ | __________ | _____</p>',
  //   s3: '<p class="stimulus">__________ | ____ | kick | __________ | _____</p>',
  //   s4: '<p class="stimulus">__________ | ____ | ____ | the zebras | _____</p>',
  //   s5: '<p class="stimulus">__________ | ____ | ____ | __________ | laugh</p>',
  //   clause_type: "sr",
  //   number: "pp",
  //   question: "<h2>Do the zebras that kick the horses laugh?</h2>",
  //   correct_answer: false,
  // },
  {
    // #4
    s0: '<p class="stimulus">__________ | ____ | ______ | __________ | ___</p>',
    s1: '<p class="stimulus">The zebras | ____ | ______ | __________ | ___</p>',
    s2: '<p class="stimulus">__________ | that | ______ | __________ | ___</p>',
    s3: '<p class="stimulus">__________ | ____ | follow | __________ | ___</p>',
    s4: '<p class="stimulus">__________ | ____ | ______ | the horses | ___</p>',
    s5: '<p class="stimulus">__________ | ____ | ______ | __________ | run</p>',
    clause_type: "sr",
    number: "pp",
    question: "<h2>Do the zebras that follow the horses run?</h2>",
    correct_answer: true,
  },
  {
    // #7
    s0: '<p class="stimulus">________ | ____ | ____ | ________ | ___</p>',
    s1: '<p class="stimulus">The dogs | ____ | ____ | ________ | ___</p>',
    s2: '<p class="stimulus">________ | that | ____ | ________ | ___</p>',
    s3: '<p class="stimulus">________ | ____ | push | ________ | ___</p>',
    s4: '<p class="stimulus">________ | ____ | ____ | the cats | ___</p>',
    s5: '<p class="stimulus">________ | ____ | ____ | ________ | cry</p>',
    clause_type: "sr",
    number: "pp",
    question: "<h2>Do the cats that push the dogs cry?</h2>",
    correct_answer: false,
  },
  {
    // #8
    s0: '<p class="stimulus">________ | ____ | ___ | ________ | _____</p>',
    s1: '<p class="stimulus">The cats | ____ | ___ | ________ | _____</p>',
    s2: '<p class="stimulus">________ | that | ___ | ________ | _____</p>',
    s3: '<p class="stimulus">________ | ____ | hug | ________ | _____</p>',
    s4: '<p class="stimulus">________ | ____ | ___ | the dogs | _____</p>',
    s5: '<p class="stimulus">________ | ____ | ___ | ________ | smile</p>',
    clause_type: "sr",
    number: "pp",
    question: "<h2>Do the cats that hug the dogs smile?</h2>",
    correct_answer: true,
  },
  // {
  //   // #10
  //   s0: '<p class="stimulus">________ | ____ | _____ | ________ | ___</p>',
  //   s1: '<p class="stimulus">The cats | ____ | _____ | ________ | ___</p>',
  //   s2: '<p class="stimulus">________ | that | _____ | ________ | ___</p>',
  //   s3: '<p class="stimulus">________ | ____ | watch | ________ | ___</p>',
  //   s4: '<p class="stimulus">________ | ____ | _____ | the dogs | ___</p>',
  //   s5: '<p class="stimulus">________ | ____ | _____ | ________ | eat</p>',
  //   clause_type: "sr",
  //   number: "pp",
  //   question: "<h2>Do the dogs that watch the cats eat?</h2>",
  //   correct_answer: false,
  // },
  {
    // #1
    s0: '<p class="stimulus">__________ | ____ | _____ | _________ | _____</p>',
    s1: '<p class="stimulus">The horses | ____ | _____ | _________ | _____</p>',
    s2: '<p class="stimulus">__________ | that | _____ | _________ | _____</p>',
    s3: '<p class="stimulus">__________ | ____ | chase | _________ | _____</p>',
    s4: '<p class="stimulus">__________ | ____ | _____ | the zebra | ____ </p>',
    s5: '<p class="stimulus">__________ | ____ | _____ | _________ | fall </p>',
    clause_type: "sr",
    number: "ps",
    question: "<h2>Do the horses that chase the zebra fall?</h2>",
    correct_answer: true,
  },
  // {
  //   // #3
  //   s0: '<p class="stimulus">__________ | ____ | ____ | _________ | _____</p>',
  //   s1: '<p class="stimulus">The horses | ____ | ____ | _________ | _____</p>',
  //   s2: '<p class="stimulus">__________ | that | ____ | _________ | _____</p>',
  //   s3: '<p class="stimulus">__________ | ____ | kick | _________ | _____</p>',
  //   s4: '<p class="stimulus">__________ | ____ | ____ | the zebra | _____</p>',
  //   s5: '<p class="stimulus">__________ | ____ | ____ | _________ | laugh</p>',
  //   clause_type: "sr",
  //   number: "ps",
  //   question: "<h2>Does the zebra that kicks the horses laugh?</h2>",
  //   correct_answer: false,
  // },
  {
    // #4
    s0: '<p class="stimulus">__________ | ____ | ______ | _________ | ___</p>',
    s1: '<p class="stimulus">The zebras | ____ | ______ | _________ | ___</p>',
    s2: '<p class="stimulus">__________ | that | ______ | _________ | ___</p>',
    s3: '<p class="stimulus">__________ | ____ | follow | _________ | ___</p>',
    s4: '<p class="stimulus">__________ | ____ | ______ | the horse | ___</p>',
    s5: '<p class="stimulus">__________ | ____ | ______ | _________ | run</p>',
    clause_type: "sr",
    number: "ps",
    question: "<h2>Do the zebras that follow the horse run?</h2>",
    correct_answer: true,
  },
  {
    // #7
    s0: '<p class="stimulus">________ | ____ | ____ | _______ | ___</p>',
    s1: '<p class="stimulus">The dogs | ____ | ____ | _______ | ___</p>',
    s2: '<p class="stimulus">________ | that | ____ | _______ | ___</p>',
    s3: '<p class="stimulus">________ | ____ | push | _______ | ___</p>',
    s4: '<p class="stimulus">________ | ____ | ____ | the cat | ___</p>',
    s5: '<p class="stimulus">________ | ____ | ____ | _______ | cry</p>',
    clause_type: "sr",
    number: "ps",
    question: "<h2>Does the cat that pushes the dogs cry?</h2>",
    correct_answer: false,
  },
  {
    // #8
    s0: '<p class="stimulus">________ | ____ | ___ | _______ | _____</p>',
    s1: '<p class="stimulus">The cats | ____ | ___ | _______ | _____</p>',
    s2: '<p class="stimulus">________ | that | ___ | _______ | _____</p>',
    s3: '<p class="stimulus">________ | ____ | hug | _______ | _____</p>',
    s4: '<p class="stimulus">________ | ____ | ___ | the dog | _____</p>',
    s5: '<p class="stimulus">________ | ____ | ___ | _______ | smile</p>',
    clause_type: "sr",
    number: "ps",
    question: "<h2>Do the cats that hug the dogs smile?</h2>",
    correct_answer: true,
  },
  // {
  //   // #10
  //   s0: '<p class="stimulus">________ | ____ | _____ | _______ | ___</p>',
  //   s1: '<p class="stimulus">The cats | ____ | _____ | _______ | ___</p>',
  //   s2: '<p class="stimulus">________ | that | _____ | _______ | ___</p>',
  //   s3: '<p class="stimulus">________ | ____ | watch | _______ | ___</p>',
  //   s4: '<p class="stimulus">________ | ____ | _____ | the dog | ___</p>',
  //   s5: '<p class="stimulus">________ | ____ | _____ | _______ | eat</p>',
  //   clause_type: "sr",
  //   number: "ps",
  //   question: "<h2>Does the dog that watches the cats eat?</h2>",
  //   correct_answer: false,
  // },
  {
    // #1
    s0: '<p class="stimulus">_________ | ____ | ______ | __________ | ______</p>',
    s1: '<p class="stimulus">The horse | ____ | ______ | __________ | ______</p>',
    s2: '<p class="stimulus">_________ | that | ______ | __________ | ______</p>',
    s3: '<p class="stimulus">_________ | ____ | chases | __________ | ______</p>',
    s4: '<p class="stimulus">_________ | ____ | ______ | the zebras | _____ </p>',
    s5: '<p class="stimulus">_________ | ____ | ______ | __________ | falls </p>',
    clause_type: "sr",
    number: "sp",
    question: "<h2>Does the horse that chases the zebras fall?</h2>",
    correct_answer: true,
  },
  // {
  //   // #3
  //   s0: '<p class="stimulus">_________ | ____ | _____ | __________ | ______</p>',
  //   s1: '<p class="stimulus">The horse | ____ | _____ | __________ | ______</p>',
  //   s2: '<p class="stimulus">_________ | that | _____ | __________ | ______</p>',
  //   s3: '<p class="stimulus">_________ | ____ | kicks | __________ | ______</p>',
  //   s4: '<p class="stimulus">_________ | ____ | _____ | the zebras | ______</p>',
  //   s5: '<p class="stimulus">_________ | ____ | _____ | __________ | laughs</p>',
  //   clause_type: "sr",
  //   number: "sp",
  //   question: "<h2>Do the zebras that kick the horse laugh?</h2>",
  //   correct_answer: false,
  // },
  {
    // #4
    s0: '<p class="stimulus">_________ | ____ | _______ | __________ | ____</p>',
    s1: '<p class="stimulus">The zebra | ____ | _______ | __________ | ____</p>',
    s2: '<p class="stimulus">_________ | that | _______ | __________ | ____</p>',
    s3: '<p class="stimulus">_________ | ____ | follows | __________ | ____</p>',
    s4: '<p class="stimulus">_________ | ____ | _______ | the horses | ____</p>',
    s5: '<p class="stimulus">_________ | ____ | _______ | __________ | runs</p>',
    clause_type: "sr",
    number: "sp",
    question: "<h2>Does the zebra that follows the horses run?</h2>",
    correct_answer: true,
  },
  {
    // #7
    s0: '<p class="stimulus">_______ | ____ | ______ | ________ | _____</p>',
    s1: '<p class="stimulus">The dog | ____ | ______ | ________ | _____</p>',
    s2: '<p class="stimulus">_______ | that | ______ | ________ | _____</p>',
    s3: '<p class="stimulus">_______ | ____ | pushes | ________ | _____</p>',
    s4: '<p class="stimulus">_______ | ____ | ______ | the cats | _____</p>',
    s5: '<p class="stimulus">_______ | ____ | ______ | ________ | cries</p>',
    clause_type: "sr",
    number: "sp",
    question: "<h2>Do the cats that push the dog cry?</h2>",
    correct_answer: false,
  },
  {
    // #8
    s0: '<p class="stimulus">_______ | ____ | ____ | ________ | ______</p>',
    s1: '<p class="stimulus">The cat | ____ | ____ | ________ | ______</p>',
    s2: '<p class="stimulus">_______ | that | ____ | ________ | ______</p>',
    s3: '<p class="stimulus">_______ | ____ | hugs | ________ | ______</p>',
    s4: '<p class="stimulus">_______ | ____ | ____ | the dogs | ______</p>',
    s5: '<p class="stimulus">_______ | ____ | ____ | ________ | smiles</p>',
    clause_type: "sr",
    number: "sp",
    question: "<h2>Does the cat that hugs the dogs smile?</h2>",
    correct_answer: true,
  },
  // {
  //   // #10
  //   s0: '<p class="stimulus">_______ | ____ | _______ | ________ | ____</p>',
  //   s1: '<p class="stimulus">The cat | ____ | _______ | ________ | ____</p>',
  //   s2: '<p class="stimulus">_______ | that | _______ | ________ | ____</p>',
  //   s3: '<p class="stimulus">_______ | ____ | watches | ________ | ____</p>',
  //   s4: '<p class="stimulus">_______ | ____ | _______ | the dogs | ____</p>',
  //   s5: '<p class="stimulus">_______ | ____ | _______ | ________ | eats</p>',
  //   clause_type: "sr",
  //   number: "sp",
  //   question: "<h2>Do the dogs that watch the cat eat?</h2>",
  //   correct_answer: false,
  // },
  {
    // Object Relatives
    // #1
    s0: '<p class="stimulus">_________ | ____ | _________ | ______ | _____</p>',
    s1: '<p class="stimulus">The horse | ____ | _________ | ______ | _____</p>',
    s2: '<p class="stimulus">_________ | that | _________ | ______ | _____</p>',
    s3: '<p class="stimulus">_________ | ____ | the zebra | ______ | _____</p>',
    s4: '<p class="stimulus">_________ | ____ | _________ | chases | _____</p>',
    s5: '<p class="stimulus">_________ | ____ | _________ | ______ | falls</p>',
    clause_type: "or",
    number: "ss",
    question: "<h2>Does the horse that the zebra chases fall?</h2>",
    correct_answer: true,
  },
  // {
  //   // #3
  //   s0: '<p class="stimulus">_________ | ____ | _________ | _____ | ______</p>',
  //   s1: '<p class="stimulus">The horse | ____ | _________ | _____ | ______</p>',
  //   s2: '<p class="stimulus">_________ | that | _________ | _____ | ______</p>',
  //   s3: '<p class="stimulus">_________ | ____ | the zebra | _____ | ______</p>',
  //   s4: '<p class="stimulus">_________ | ____ | _________ | kicks | ______</p>',
  //   s5: '<p class="stimulus">_________ | ____ | _________ | _____ | laughs</p>',
  //   clause_type: "or",
  //   number: "ss",
  //   question: "<h2>Does the zebra that the horse kicks laugh?</h2>",
  //   correct_answer: false,
  // },
  {
    // #4
    s0: '<p class="stimulus">_________ | ____ | ________ | _______ | ____</p>',
    s1: '<p class="stimulus">The zebra | ____ | ________ | _______ | ____</p>',
    s2: '<p class="stimulus">_________ | that | ________ | _______ | ____</p>',
    s3: '<p class="stimulus">_________ | ____ | the horse| _______ | ____</p>',
    s4: '<p class="stimulus">_________ | ____ | ________ | follows | ____</p>',
    s5: '<p class="stimulus">_________ | ____ | ________ | _______ | runs</p>',
    clause_type: "or",
    number: "ss",
    question: "<h2>Does the zebra that the horse follows run?</h2>",
    correct_answer: true,
  },
  {
    // #7
    s0: '<p class="stimulus">_______ | ____ | _______ | ______ | _____</p>',
    s1: '<p class="stimulus">The dog | ____ | _______ | ______ | _____</p>',
    s2: '<p class="stimulus">_______ | that | _______ | ______ | _____</p>',
    s3: '<p class="stimulus">_______ | ____ | the cat | ______ | _____</p>',
    s4: '<p class="stimulus">_______ | ____ | _______ | pushes | _____</p>',
    s5: '<p class="stimulus">_______ | ____ | _______ | ______ | cries</p>',
    clause_type: "or",
    number: "ss",
    question: "<h2>Does the cat that the dog pushes cry?</h2>",
    correct_answer: false,
  },
  {
    // #8
    s0: '<p class="stimulus">_______ | ____ | _______ | ____ | ______</p>',
    s1: '<p class="stimulus">The cat | ____ | _______ | ____ | ______</p>',
    s2: '<p class="stimulus">_______ | that | _______ | ____ | ______</p>',
    s3: '<p class="stimulus">_______ | ____ | the dog | ____ | ______</p>',
    s4: '<p class="stimulus">_______ | ____ | _______ | hugs | ______</p>',
    s5: '<p class="stimulus">_______ | ____ | _______ | ____ | smiles</p>',
    clause_type: "or",
    number: "ss",
    question: "<h2>Does the cat that the dog hugs smile?",
    correct_answer: true,
  },
  // {
  //   // #10
  //   s0: '<p class="stimulus">_______ | ____ | _______ | _______ | ____</p>',
  //   s1: '<p class="stimulus">The cat | ____ | _______ | _______ | ____</p>',
  //   s2: '<p class="stimulus">_______ | that | _______ | _______ | ____</p>',
  //   s3: '<p class="stimulus">_______ | ____ | the dog | _______ | ____</p>',
  //   s4: '<p class="stimulus">_______ | ____ | _______ | watches | ____</p>',
  //   s5: '<p class="stimulus">_______ | ____ | _______ | _______ | eats</p>',
  //   clause_type: "or",
  //   number: "ss",
  //   question: "<h2>Does the dog that the cat watches eat?</h2>",
  //   correct_answer: false,
  // },
  {
    // #1
    s0: '<p class="stimulus">__________ | ____ | __________ | _____ | ____</p>',
    s1: '<p class="stimulus">The horses | ____ | __________ | _____ | ____</p>',
    s2: '<p class="stimulus">__________ | that | __________ | _____ | ____</p>',
    s3: '<p class="stimulus">__________ | ____ | the zebras | _____ | ____</p>',
    s4: '<p class="stimulus">__________ | ____ | __________ | chase | ___ </p>',
    s5: '<p class="stimulus">__________ | ____ | __________ | _____ | fall</p>',
    clause_type: "or",
    number: "pp",
    question: "<h2>Do the horses that the zebras chase fall?</h2>",
    correct_answer: true,
  },
  // {
  //   // #3
  //   s0: '<p class="stimulus">__________ | ____ | __________ | ____ | _____</p>',
  //   s1: '<p class="stimulus">The horses | ____ | __________ | ____ | _____</p>',
  //   s2: '<p class="stimulus">__________ | that | __________ | ____ | _____</p>',
  //   s3: '<p class="stimulus">__________ | ____ | the zebras | ____ | _____</p>',
  //   s4: '<p class="stimulus">__________ | ____ | __________ | kick | _____</p>',
  //   s5: '<p class="stimulus">__________ | ____ | __________ | ____ | laugh</p>',
  //   clause_type: "or",
  //   number: "pp",
  //   question: "<h2>Do the zebras that the horses kick laugh?</h2>",
  //   correct_answer: false,
  // },
  {
    // #4
    s0: '<p class="stimulus">__________ | ____ | __________ | ______ | ___</p>',
    s1: '<p class="stimulus">The zebras | ____ | __________ | ______ | ___</p>',
    s2: '<p class="stimulus">__________ | that | __________ | ______ | ___</p>',
    s3: '<p class="stimulus">__________ | ____ | the horses | ______ | ___</p>',
    s4: '<p class="stimulus">__________ | ____ | __________ | follow | ___</p>',
    s5: '<p class="stimulus">__________ | ____ | __________ | ______ | run</p>',
    clause_type: "or",
    number: "pp",
    question: "<h2>Do the zebras that the horses follow run?</h2>",
    correct_answer: true,
  },
  {
    // #7
    s0: '<p class="stimulus">________ | ____ | ________ | ____ | ___</p>',
    s1: '<p class="stimulus">The dogs | ____ | ________ | ____ | ___</p>',
    s2: '<p class="stimulus">________ | that | ________ | ____ | ___</p>',
    s3: '<p class="stimulus">________ | ____ | the cats | ____ | ___</p>',
    s4: '<p class="stimulus">________ | ____ | ________ | push | ___</p>',
    s5: '<p class="stimulus">________ | ____ | ________ | ____ | cry</p>',
    clause_type: "or",
    number: "pp",
    question: "<h2>Do the cats that the dogs push cry?</h2>",
    correct_answer: false,
  },
  {
    // #8
    s0: '<p class="stimulus">________ | ____ | ________ | ___ | _____</p>',
    s1: '<p class="stimulus">The cats | ____ | ________ | ___ | _____</p>',
    s2: '<p class="stimulus">________ | that | ________ | ___ | _____</p>',
    s3: '<p class="stimulus">________ | ____ | the dogs | ___ | _____</p>',
    s4: '<p class="stimulus">________ | ____ | ________ | hug | _____</p>',
    s5: '<p class="stimulus">________ | ____ | ________ | ___ | smile</p>',
    clause_type: "or",
    number: "pp",
    question: "<h2>Do the cats that the dogs hug smile?</h2>",
    correct_answer: true,
  },
  // {
  //   // #10
  //   s0: '<p class="stimulus">________ | ____ | ________ | _____ | ___</p>',
  //   s1: '<p class="stimulus">The cats | ____ | ________ | _____ | ___</p>',
  //   s2: '<p class="stimulus">________ | that | ________ | _____ | ___</p>',
  //   s3: '<p class="stimulus">________ | ____ | the dogs | _____ | ___</p>',
  //   s4: '<p class="stimulus">________ | ____ | ________ | watch | ___</p>',
  //   s5: '<p class="stimulus">________ | ____ | ________ | _____ | eat</p>',
  //   clause_type: "or",
  //   number: "pp",
  //   question: "<h2>Do the dogs that the cats watch eat?</h2>",
  //   correct_answer: false,
  // },
  {
    // #1
    s0: '<p class="stimulus">__________ | ____ | _________ | ______ | _____</p>',
    s1: '<p class="stimulus">The horses | ____ | _________ | ______ | _____</p>',
    s2: '<p class="stimulus">__________ | that | _________ | ______ | _____</p>',
    s3: '<p class="stimulus">__________ | ____ | the zebra | ______ | _____</p>',
    s4: '<p class="stimulus">__________ | ____ | _________ | chases | ____ </p>',
    s5: '<p class="stimulus">__________ | ____ | _________ | ______ | fall </p>',
    clause_type: "or",
    number: "ps",
    question: "<h2>Do the horses tha the zebra chases fall?</h2>",
    correct_answer: true,
  },
  // {
  //   // #3
  //   s0: '<p class="stimulus">__________ | ____ | _________ | _____ | _____</p>',
  //   s1: '<p class="stimulus">The horses | ____ | _________ | _____ | _____</p>',
  //   s2: '<p class="stimulus">__________ | that | _________ | _____ | _____</p>',
  //   s3: '<p class="stimulus">__________ | ____ | the zebra | _____ | _____</p>',
  //   s4: '<p class="stimulus">__________ | ____ | _________ | kicks | _____</p>',
  //   s5: '<p class="stimulus">__________ | ____ | _________ | _____ | laugh</p>',
  //   clause_type: "or",
  //   number: "ps",
  //   question: "<h2>Does the zebra that the horses chase laugh?</h2>",
  //   correct_answer: false,
  // },
  {
    // #4
    s0: '<p class="stimulus">__________ | ____ | _________ | _______ | ___</p>',
    s1: '<p class="stimulus">The zebras | ____ | _________ | _______ | ___</p>',
    s2: '<p class="stimulus">__________ | that | _________ | _______ | ___</p>',
    s3: '<p class="stimulus">__________ | ____ | the horse | _______ | ___</p>',
    s4: '<p class="stimulus">__________ | ____ | _________ | follows | ___</p>',
    s5: '<p class="stimulus">__________ | ____ | _________ | _______ | run</p>',
    clause_type: "or",
    number: "ps",
    question: "<h2>Do the zebras that the horse follows run?</h2>",
    correct_answer: true,
  },
  {
    // #7
    s0: '<p class="stimulus">________ | ____ | _______ | ______ | ___</p>',
    s1: '<p class="stimulus">The dogs | ____ | _______ | ______ | ___</p>',
    s2: '<p class="stimulus">________ | that | _______ | ______ | ___</p>',
    s3: '<p class="stimulus">________ | ____ | the cat | ______ | ___</p>',
    s4: '<p class="stimulus">________ | ____ | _______ | pushes | ___</p>',
    s5: '<p class="stimulus">________ | ____ | _______ | ______ | cry</p>',
    clause_type: "or",
    number: "ps",
    question: "<h2>Does the cat that the dogs push cry?</h2>",
    correct_answer: false,
  },
  {
    // #8
    s0: '<p class="stimulus">________ | ____ | _______ | ____ | _____</p>',
    s1: '<p class="stimulus">The cats | ____ | _______ | ____ | _____</p>',
    s2: '<p class="stimulus">________ | that | _______ | ____ | _____</p>',
    s3: '<p class="stimulus">________ | ____ | the dog | ____ | _____</p>',
    s4: '<p class="stimulus">________ | ____ | _______ | hugs | _____</p>',
    s5: '<p class="stimulus">________ | ____ | _______ | ____ | smile</p>',
    clause_type: "or",
    number: "ps",
    question: "<h2>Do the cats that the dog hugs smile?</h2>",
    correct_answer: true,
  },
  // {
  //   // #10
  //   s0: '<p class="stimulus">________ | ____ | _______ | _______ | ___</p>',
  //   s1: '<p class="stimulus">The cats | ____ | _______ | _______ | ___</p>',
  //   s2: '<p class="stimulus">________ | that | _______ | _______ | ___</p>',
  //   s3: '<p class="stimulus">________ | ____ | the dog | _______ | ___</p>',
  //   s4: '<p class="stimulus">________ | ____ | _______ | watches | ___</p>',
  //   s5: '<p class="stimulus">________ | ____ | _______ | _______ | eat</p>',
  //   clause_type: "or",
  //   number: "ps",
  //   question: "<h2>Does the dog that the cats watch eat?</h2>",
  //   correct_answer: false,
  // },
  {
    // #1
    s0: '<p class="stimulus">_________ | ____ | __________ | _____ | _____</p>',
    s1: '<p class="stimulus">The horse | ____ | __________ | _____ | _____</p>',
    s2: '<p class="stimulus">_________ | that | __________ | _____ | _____</p>',
    s3: '<p class="stimulus">_________ | ____ | the zebras | _____ | _____</p>',
    s4: '<p class="stimulus">_________ | ____ | __________ | chase | ____ </p>',
    s5: '<p class="stimulus">_________ | ____ | __________ | _____ | falls</p>',
    clause_type: "or",
    number: "sp",
    question: "<h2>Does the horse that the zebras chase fall?</h2>",
    correct_answer: true,
  },
  // {
  //   // #3
  //   s0: '<p class="stimulus">_________ | ____ | __________ | ____ | ______</p>',
  //   s1: '<p class="stimulus">The horse | ____ | __________ | ____ | ______</p>',
  //   s2: '<p class="stimulus">_________ | that | __________ | ____ | ______</p>',
  //   s3: '<p class="stimulus">_________ | ____ | the zebras | ____ | ______</p>',
  //   s4: '<p class="stimulus">_________ | ____ | __________ | kick | ______</p>',
  //   s5: '<p class="stimulus">_________ | ____ | __________ | ____ | laughs</p>',
  //   clause_type: "or",
  //   number: "sp",
  //   question: "<h2>Do the zebras that the horse kicks laugh?</h2>",
  //   correct_answer: false,
  // },
  {
    // #4
    s0: '<p class="stimulus">_________ | ____ | __________ | ______ | ____</p>',
    s1: '<p class="stimulus">The zebra | ____ | __________ | ______ | ____</p>',
    s2: '<p class="stimulus">_________ | that | __________ | ______ | ____</p>',
    s3: '<p class="stimulus">_________ | ____ | the horses | ______ | ____</p>',
    s4: '<p class="stimulus">_________ | ____ | __________ | follow | ____</p>',
    s5: '<p class="stimulus">_________ | ____ | __________ | ______ | runs</p>',
    clause_type: "or",
    number: "sp",
    question: "<h2>Does the zebra that the horses follow run?</h2>",
    correct_answer: true,
  },
  {
    // #7
    s0: '<p class="stimulus">_______ | ____ | ________ | ____ | _____</p>',
    s1: '<p class="stimulus">The dog | ____ | ________ | ____ | _____</p>',
    s2: '<p class="stimulus">_______ | that | ________ | ____ | _____</p>',
    s3: '<p class="stimulus">_______ | ____ | the cats | ____ | _____</p>',
    s4: '<p class="stimulus">_______ | ____ | ________ | push | _____</p>',
    s5: '<p class="stimulus">_______ | ____ | ________ | ____ | cries</p>',
    clause_type: "or",
    number: "sp",
    question: "<h2>Do the cats that the dog pushes cry?</h2>",
    correct_answer: false,
  },
  {
    // #8
    s0: '<p class="stimulus">_______ | ____ | ________ | ___ | ______</p>',
    s1: '<p class="stimulus">The cat | ____ | ________ | ___ | ______</p>',
    s2: '<p class="stimulus">_______ | that | ________ | ___ | ______</p>',
    s3: '<p class="stimulus">_______ | ____ | the dogs | ___ | ______</p>',
    s4: '<p class="stimulus">_______ | ____ | ________ | hug | ______</p>',
    s5: '<p class="stimulus">_______ | ____ | ________ | ___ | smiles</p>',
    clause_type: "or",
    number: "sp",
    question: "<h2>Does the cat that the dogs hug smile?",
    correct_answer: true,
  },
  // {
  //   // #10
  //   s0: '<p class="stimulus">_______ | ____ | ________ | _____ | ____</p>',
  //   s1: '<p class="stimulus">The cat | ____ | ________ | _____ | ____</p>',
  //   s2: '<p class="stimulus">_______ | that | ________ | _____ | ____</p>',
  //   s3: '<p class="stimulus">_______ | ____ | the dogs | _____ | ____</p>',
  //   s4: '<p class="stimulus">_______ | ____ | ________ | watch | ____</p>',
  //   s5: '<p class="stimulus">_______ | ____ | ________ | _____ | eats</p>',
  //   clause_type: "or",
  //   number: "sp",
  //   question: "<h2>Do the dogs that the cat watches eat?</h2>",
  //   correct_answer: false,
  // },
  {
    // Fillers
    // #1
    s0: '<p class="stimulus">________ | ___ | _______ | _______ | _____</p>',
    s1: '<p class="stimulus">The chef | ___ | _______ | _______ | _____</p>',
    s2: '<p class="stimulus">________ | who | _______ | _______ | _____</p>',
    s3: '<p class="stimulus">________ | ___ | carries |________ | _____</p>',
    s4: '<p class="stimulus">________ | ___ | _______ | the box | _____</p>',
    s5: '<p class="stimulus">________ | ___ | _______ | _______ | falls</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the chef who carries the box fall?</h2>",
    correct_answer: true,
  },
  {
    // #2
    s0: '<p class="stimulus">________ | ___ | _____ | _______ | _____</p>',
    s1: '<p class="stimulus">The chef | ___ | _____ | _______ | _____</p>',
    s2: '<p class="stimulus">________ | who | _____ | _______ | _____</p>',
    s3: '<p class="stimulus">________ | ___ | grabs |________ | _____</p>',
    s4: '<p class="stimulus">________ | ___ | _____ | the box | _____</p>',
    s5: '<p class="stimulus">________ | ___ | _____ | _______ | jumps</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the box that the chef grabs fall?</h2>",
    correct_answer: false,
  },
  {
    // #3
    s0: '<p class="stimulus">________ | ___ | _____ | _______ | ______</p>',
    s1: '<p class="stimulus">The chef | ___ | _____ | _______ | ______</p>',
    s2: '<p class="stimulus">________ | who | _____ | _______ | ______</p>',
    s3: '<p class="stimulus">________ | ___ | opens |________ | ______</p>',
    s4: '<p class="stimulus">________ | ___ | _____ | the box | ______</p>',
    s5: '<p class="stimulus">________ | ___ | _____ | _______ | smiles</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the chef who opens the box smile?</h2>",
    correct_answer: true,
  },
  {
    // #4
    s0: '<p class="stimulus">________ | ___ | ______ | _______ | _______</p>',
    s1: '<p class="stimulus">The chef | ___ | ______ | _______ | _______</p>',
    s2: '<p class="stimulus">________ | who | ______ | _______ | _______</p>',
    s3: '<p class="stimulus">________ | ___ | throws |________ | _______</p>',
    s4: '<p class="stimulus">________ | ___ | ______ | the box | _______</p>',
    s5: '<p class="stimulus">________ | ___ | ______ | _______ | screams</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the chef who opens the box cry?</h2>",
    correct_answer: false,
  },
  {
    // #5
    s0: '<p class="stimulus">________ | ___ | _____ | _______ | _____</p>',
    s1: '<p class="stimulus">The chef | ___ | _____ | _______ | _____</p>',
    s2: '<p class="stimulus">________ | who | _____ | _______ | _____</p>',
    s3: '<p class="stimulus">________ | ___ | kicks |________ | _____</p>',
    s4: '<p class="stimulus">________ | ___ | _____ | the box | _____</p>',
    s5: '<p class="stimulus">________ | ___ | _____ | _______ | cries</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the chef who kicks the box cry?</h2>",
    correct_answer: true,
  },
  {
    // #6
    s0: '<p class="stimulus">__________ | ___ | _____ | __________ | _____</p>',
    s1: '<p class="stimulus">The singer | ___ | _____ | __________ | _____</p>',
    s2: '<p class="stimulus">__________ | who | _____ | __________ | _____</p>',
    s3: '<p class="stimulus">__________ | ___ | plays |___________ | _____</p>',
    s4: '<p class="stimulus">__________ | ___ | _____ | the guitar | _____</p>',
    s5: '<p class="stimulus">__________ | ___ | _____ | __________ | sings</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the singer who plays the guitar cry?</h2>",
    correct_answer: false,
  },
  {
    // #7
    s0: '<p class="stimulus">__________ | ___ | _____ | __________ | _____</p>',
    s1: '<p class="stimulus">The singer | ___ | _____ | __________ | _____</p>',
    s2: '<p class="stimulus">__________ | who | _____ | __________ | _____</p>',
    s3: '<p class="stimulus">__________ | ___ | grabs |___________ | _____</p>',
    s4: '<p class="stimulus">__________ | ___ | _____ | the guitar | _____</p>',
    s5: '<p class="stimulus">__________ | ___ | _____ | __________ | cries</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the singer who grabs the guitar cry?</h2>",
    correct_answer: true,
  },
  {
    // #8
    s0: '<p class="stimulus">__________ | ___ | _______ | __________ | _____</p>',
    s1: '<p class="stimulus">The singer | ___ | _______ | __________ | _____</p>',
    s2: '<p class="stimulus">__________ | who | _______ | __________ | _____</p>',
    s3: '<p class="stimulus">__________ | ___ | smashes |___________ | _____</p>',
    s4: '<p class="stimulus">__________ | ___ | _______ | the guitar | _____</p>',
    s5: '<p class="stimulus">__________ | ___ | _______ | __________ | cries</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the singer who smashes the guitar smile?</h2>",
    correct_answer: false,
  },
  {
    // #9
    s0: '<p class="stimulus">__________ | ___ | ______ | __________ | _______</p>',
    s1: '<p class="stimulus">The singer | ___ | ______ | __________ | _______</p>',
    s2: '<p class="stimulus">__________ | who | ______ | __________ | _______</p>',
    s3: '<p class="stimulus">__________ | ___ | throws |___________ | _______</p>',
    s4: '<p class="stimulus">__________ | ___ | ______ | the guitar | _______</p>',
    s5: '<p class="stimulus">__________ | ___ | ______ | __________ | screams</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the singer who throws the guitar scream?</h2>",
    correct_answer: true,
  },
  {
    // #10
    s0: '<p class="stimulus">__________ | ___ | ______ | __________ | _______</p>',
    s1: '<p class="stimulus">The singer | ___ | ______ | __________ | _______</p>',
    s2: '<p class="stimulus">__________ | who | ______ | __________ | _______</p>',
    s3: '<p class="stimulus">__________ | ___ | stores |___________ | _______</p>',
    s4: '<p class="stimulus">__________ | ___ | ______ | the guitar | _______</p>',
    s5: '<p class="stimulus">__________ | ___ | ______ | __________ | murmurs</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the singer who stores the guitar cry?</h2>",
    correct_answer: false,
  },
  {
    // #11
    s0: '<p class="stimulus">_________ | ___ | ______ | __________ | ______</p>',
    s1: '<p class="stimulus">The woman | ___ | ______ | __________ | ______</p>',
    s2: '<p class="stimulus">_________ | who | ______ | __________ | ______</p>',
    s3: '<p class="stimulus">_________ | ___ | writes |___________ | ______</p>',
    s4: '<p class="stimulus">_________ | ___ | ______ | the letter | ______</p>',
    s5: '<p class="stimulus">_________ | ___ | ______ | __________ | smiles</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the woman who writes the letter smile?</h2>",
    correct_answer: true,
  },
  {
    // #12
    s0: '<p class="stimulus">_________ | ___ | _____ | __________ | _______</p>',
    s1: '<p class="stimulus">The woman | ___ | _____ | __________ | _______</p>',
    s2: '<p class="stimulus">_________ | who | _____ | __________ | _______</p>',
    s3: '<p class="stimulus">_________ | ___ | reads |___________ | _______</p>',
    s4: '<p class="stimulus">_________ | ___ | _____ | the letter | _______</p>',
    s5: '<p class="stimulus">_________ | ___ | _____ | __________ | screams</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the woman who reads the letter cry?</h2>",
    correct_answer: false,
  },
  {
    // #13
    s0: '<p class="stimulus">_________ | ___ | _____ | __________ | ______</p>',
    s1: '<p class="stimulus">The woman | ___ | _____ | __________ | ______</p>',
    s2: '<p class="stimulus">_________ | who | _____ | __________ | ______</p>',
    s3: '<p class="stimulus">_________ | ___ | burns |___________ | ______</p>',
    s4: '<p class="stimulus">_________ | ___ | _____ | the letter | ______</p>',
    s5: '<p class="stimulus">_________ | ___ | _____ | __________ | leaves</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the woman who burns the letter leave?</h2>",
    correct_answer: true,
  },
  {
    // #14
    s0: '<p class="stimulus">_________ | ___ | ______ | __________ | ______</p>',
    s1: '<p class="stimulus">The woman | ___ | ______ | __________ | ______</p>',
    s2: '<p class="stimulus">_________ | who | ______ | __________ | ______</p>',
    s3: '<p class="stimulus">_________ | ___ | throws |___________ | ______</p>',
    s4: '<p class="stimulus">_________ | ___ | ______ | the letter | ______</p>',
    s5: '<p class="stimulus">_________ | ___ | ______ | __________ | screams</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the woman who throws the letter smile?</h2>",
    correct_answer: false,
  },
  {
    // #15
    s0: '<p class="stimulus">_________ | ___ | ______ | __________ | ______</p>',
    s1: '<p class="stimulus">The woman | ___ | ______ | __________ | ______</p>',
    s2: '<p class="stimulus">_________ | who | ______ | __________ | ______</p>',
    s3: '<p class="stimulus">_________ | ___ | stores |___________ | ______</p>',
    s4: '<p class="stimulus">_________ | ___ | ______ | the letter | ______</p>',
    s5: '<p class="stimulus">_________ | ___ | ______ | __________ | murmurs</p>',
    clause_type: "sr-fill",
    number: "ss-fill",
    question: "<h2>Does the woman who stores the letter murmur?</h2>",
    correct_answer: true,
  },
];
